name: animestream
description: "A app made to stream and download anime!"
publish_to: 'none' #Dont remove this!


version: 1.3.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Network, parsing deps
  http: ^1.2.0
  html: ^0.15.4
  graphql: ^5.1.3
  encrypt: ^5.0.3
  js_unpack: ^1.0.4
  url_launcher: ^6.2.5
  
  # Core utils
  path_provider: ^2.0.11
  awesome_notifications: ^0.9.2
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Media and player related
  open_file: ^3.3.2
  wakelock: ^0.6.2
  better_player:
    git: 
      url: https://github.com/frostnova721/betterplayer.git

  # UI
  flutter_floating_bottom_bar: ^1.2.0
  pull_to_refresh: ^2.0.0
  flutter_markdown: ^0.6.20
  webview_flutter: ^4.7.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2

  # Misc
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  win32: ^5.2.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#181818"
  color_dark: "#181818"
  image: "lib/assets/icons/logo_foreground_splash.png"
  image_dark: "lib/assets/icons/logo_foreground_splash.png"

  android_12:
    image: "lib/assets/icons/logo_foreground_splash.png"
#     image_dark: "lib/assets/icons/logo_foreground_splash.png"
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./lib/assets/icons/logo.png"
  adaptive_icon_background: "./lib/assets/icons/logo_background.png"
  adaptive_icon_foreground: "./lib/assets/icons/logo_foreground.png"
  adaptive_icon_monochrome: "./lib/assets/icons/logo_monochrome.png"
  

  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/search.png
    - lib/assets/images/broken_heart.png
    - lib/assets/images/shines.png
    - lib/assets/images/check.png
    - lib/assets/images/ghost.png
    - lib/assets/icons/logo_foreground.png
    - lib/assets/icons/logo_monochrome.png
    - lib/assets/images/chisato.jpeg
    - lib/assets/images/mitsuha.jpg
    - lib/assets/images/profile_banner.jpg
    - lib/assets/images/chisato_AI.png


  fonts:
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Medium.ttf
    - family: NunitoSans
      fonts:
        - asset: lib/assets/fonts/NunitoSans_10pt-Medium.ttf
          style: normal
    - family: NotoSans
      fonts:
        - asset: lib/assets/fonts/NotoSans-Regular.ttf
          style: normal
        - asset: lib/assets/fonts/NotoSans-Bold.ttf
    - family: Poppins
      fonts: 
        - asset: lib/assets/fonts/Poppins-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
